# Generated by Django 3.1.6 on 2021-02-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20210203_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='approve_reject',
            field=models.CharField(blank=True, choices=[('approve', 'true'), ('app', 'false')], default='', max_length=128, verbose_name='Approve or reject an article'),
        ),
    ]
