apiVersion: v1
kind: Deployment
metadata:
  name: blog-deployment
  labels:
    app: blogI1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogI1
  template:
    metadata:
      labels:
        app: blogI1
    spec:
      containers:
      - name: blog-app
        image: blog:1.0.0
        ports:
        - containerPort: 3031
      - name: blog-db
        image: db:postgres:latest
        ports:
        - containerPort: 5432
        